//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metrovalencia.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Metrovalencia.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send feedback.
        /// </summary>
        public static string AboutFeedback {
            get {
                return ResourceManager.GetString("AboutFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string AboutLine1 {
            get {
                return ResourceManager.GetString("AboutLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HeliaSar Productions.
        /// </summary>
        public static string AboutLine2 {
            get {
                return ResourceManager.GetString("AboutLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://steelcode.net.
        /// </summary>
        public static string AboutLink {
            get {
                return ResourceManager.GetString("AboutLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arrival stop.
        /// </summary>
        public static string Arrival {
            get {
                return ResourceManager.GetString("Arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is only available in the full version. Click the buy button bellow in order to purchase the full version..
        /// </summary>
        public static string BuyNowMessage {
            get {
                return ResourceManager.GetString("BuyNowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to departure stop.
        /// </summary>
        public static string Departure {
            get {
                return ResourceManager.GetString("Departure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        public static string FavoritePageName {
            get {
                return ResourceManager.GetString("FavoritePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string FavoritePageSave {
            get {
                return ResourceManager.GetString("FavoritePageSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorite.
        /// </summary>
        public static string FavoritePageTitle {
            get {
                return ResourceManager.GetString("FavoritePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string HeaderAbout {
            get {
                return ResourceManager.GetString("HeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        public static string HeaderFavorites {
            get {
                return ResourceManager.GetString("HeaderFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maps.
        /// </summary>
        public static string HeaderMaps {
            get {
                return ResourceManager.GetString("HeaderMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string HeaderSearch {
            get {
                return ResourceManager.GetString("HeaderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arrival time.
        /// </summary>
        public static string MainPageArrivalTime {
            get {
                return ResourceManager.GetString("MainPageArrivalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to departure time.
        /// </summary>
        public static string MainPageDepartureTime {
            get {
                return ResourceManager.GetString("MainPageDepartureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string MainPageSearch {
            get {
                return ResourceManager.GetString("MainPageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trip date.
        /// </summary>
        public static string MainPageTripDate {
            get {
                return ResourceManager.GetString("MainPageTripDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin to home.
        /// </summary>
        public static string MenuPinTile {
            get {
                return ResourceManager.GetString("MenuPinTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new favorite.
        /// </summary>
        public static string NewFavoriteButton {
            get {
                return ResourceManager.GetString("NewFavoriteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string ResultsPageAppBarSave {
            get {
                return ResourceManager.GetString("ResultsPageAppBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timetable.
        /// </summary>
        public static string ResultsPageTitle {
            get {
                return ResourceManager.GetString("ResultsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stops.
        /// </summary>
        public static string SelectStopPageTitle {
            get {
                return ResourceManager.GetString("SelectStopPageTitle", resourceCulture);
            }
        }
    }
}
